version: '3'

services:
  src:
    image: src
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
        - mysql
        - redis
    command: ["./wait-for-it.sh", "mysql:3306", "-t", "30", "--", "dotnet", "src.dll"]

  redis:
    image: redis:alpine

  mysql:
    image: mysql
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_DATABASE: "HTLLBB"
        MYSQL_USER: "aspnet"
        MYSQL_PASSWORD: "aspnet"